### ISSUE TITLE
OTBR Addon ip6tables Error

### ISSUE THREAD

**Issue by LucaOverflow** [home-assistant/addons-development#102]
Hello there,

When starting the Addon (with the OTBR-Firewall disabled) I get the following Error:
`ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.`

I started it without the firewall to exclude any problems that it could bring to the table on top. However if I start it with the Firewall enabled I get the following Error:
`otbr-agent[135]: 49d.17:12:30.225 [C] Platform------: RCP API Version 7 is not in the supported range [4-6]
otbr-agent[135]: 49d.17:12:30.225 [C] Platform------: CheckRcpApiVersion() at radio_spinel_impl.hpp:423: RadioSpinelIncompatible`

and 

`ipset v7.10: Set cannot be destroyed: it is in use by a kernel component`

The last Error could maybe be the same Problem as the one without the Firewall?
However the API-Version Error confuses me a bit since it's not shown if started without the Firewall. But I guess these are two independent problems.

Thank you in advance :)

**Comment by JuliusBlueTek** [comment]
RCP API Version 7 is not in the supported range [4-6] has to do with the radio co-processor. Are you using a ot-nrf528xx? If so if you build the latest version you get that error https://github.com/openthread/ot-nrf528xx. I used the firmware from https://golioth.github.io/golioth-openthread-demo-docs/docs/create-rcp and it works. For the ip6tables if you run open thread at boot it usually works otherwise you need to do sudo modprobe ip6table_filter.

**Comment by LucaOverflow** [comment]
Thank you very much for your advice. I will try it with the other firmware and let it start on boot.

**Comment by LucaOverflow** [comment]
Thanks a lot. With the firmware you provided it works + I don't have to compile it myself.
